apiVersion: apps/v1
kind: Deployment
metadata:
  name: golf-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golf-web
  template:
    metadata:
      labels:
        app: golf-web
    spec:
      containers:
      - name: myweb
        image: gmalewicz/golf-web
        envFrom:
        - configMapRef:
            name: golf-web-configmap
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
         - containerPort: 80
           name: http
         - containerPort: 443
           name: https
        volumeMounts:
        - mountPath: "/cert"
          name: cert-storage
      volumes:
        - name: cert-storage
          persistentVolumeClaim:
            claimName:  golf-web-pvc
